### PR TITLE
Feature/discovery

### PR DESCRIPTION
**Pull request by monstergarden**
first release of the discovery feature.

### CODE REVIEW

**Comment by thecoder75** [comment]
Approved.  Changes have been added to the main tree and will be updated before next full push and build.

**Comment by thecoder75** [comment]
Example results layout:
```javascript

    LiveMe.getUserInfo(list[index].key).then(user => {

        var p = Math.floor((list[index].value / max) * 1000) / 10;
        var prettydate = require('pretty-date');
        var sex = entry.sex < 0 ? '' : (entry.sex == 0 ? 'is-female' : 'is-male'), 
            seenRaw = DataManager.wasProfileViewed(entry.uid),
            seenDate = seenRaw != false ? prettydate.format(seenRaw) : '',
            seen = seenRaw != false ? 'bright blue' : 'dim',
            bookmarked = DataManager.isBookmarked(entry) ? 'star-full bright yellow' : 'star-empty dim';

        $('#crawler-list').append(`
                    <tr id="entry-${user.user_info.uid}" onClick="showUser('${user.user_info.uid}')" style="cursor: pointer;">
                        <td width="64">
                            <img src="${user.user_info.face}" style="height: 64px; width: 64px;" onError="$(this).hide()" align="bottom" class="avatar">
                        </td>
                        <td width="90%">
                            <div class="seen" title="Last seen ${seenDate}"><i class="icon icon-eye ${seen}"></i></div>
                            <div class="bookmarked"><i class="icon icon-${bookmarked}"></i></div>
                            <h1>
                                ${user.user_info.nickname}
                                <span style="float: right; font-size: 10pt; font-weight: 600;">${p}%</span>
                            </h1>

                            <div class="countrylevel">
                                ${entry.countryCode}&nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp;<b>Level:</b> ${entry.level}
                                <div class="cell" style="width: 160px; text-align: right;">
                                    ${seenDate}
                                </div>
                            </div>
                        </td>
                    </tr>
        `);
        index++;

        setImmediate(() => { drawEntry(); });
        
    });
```

**Comment by monstergarden** [comment]
why did you delete the appollus module? Can you be more specificy about: Coding style needs to be updated to match project's coding style before approval is granted.
Which files do you mean?

**Comment by thecoder75** [comment]
The format you wrote your module in is not as standard like the custom modules used in the project now.  My attempts to clean up or try and adjust things causes your module and code to break, sometimes even killing Electron processes.  

The fact your output lists are just UserIDs without any additional information is not very professional.  People don't know what ones they've already visited and what ones they haven't.  This is why I provided the updated sample rendering code for the results list.

Also you took the code for the main view window to use for a popup window without following the standard layout I use for popup or secondary windows.

Yes I left a couple things in the main code for reference and use later on when you have your code updated and its more stable to add to the project.

**Pull request merged**
