### PR TITLE
[DO NOT MERGE] Small Linux improvements

### PR DESCRIPTION
**Pull request by mustang-sally**
Hey! Here are some small (but important) improvements for Linux. The most important one being the switch from `.tar.gz` to `AppImage`. Let me know what you think about that.

In my next post I'll be talking about updating the [Source Sans Pro font](https://github.com/adobe-fonts/source-sans-pro/tree/release/WOFF/OTF) to make it look better on Linux. I haven't pushed the commit that addresses that yet, because I want to be sure you're okay with that, since it affects the Windows font as well. I'll be posting some screenshots for comparison below.

### CODE REVIEW

**Comment by thecoder75** [comment]
Out of curiosity, what is the benefit of switching to AppImage for Linux instead of TAR.GZ archive?  How many Linux distributions support running AppImages?

**Comment by thecoder75** [comment]
Please open an Issue to discuss the font change as this I would like others to weigh on as well, specially if anyone else besides me thinks the font needs to change completely too.

**Comment by mustang-sally** [comment]
In theory, it should run out-of-the-box in any major distribution. I've added some "PROs" about AppImage in the description of my commit, but a FAQ is available [here](https://docs.appimage.org/user-guide/faq.html) and some other useful information [here](https://docs.appimage.org/user-guide/run-appimages.html).

**Comment by mustang-sally** [comment]
I also agree about changing the font, I just thought updating it would be easier. I've created a thread for discussing about that: https://github.com/thecoder75/liveme-pro-tools/issues/47

**Comment by mustang-sally** [comment]
Since those small modifications were already pushed to master, I think I should close this one. If I think of anything else I'll open another one. Thanks!

**Pull request closed without merging**
