### PR TITLE
New internal player

### PR DESCRIPTION
**Pull request by mustang-sally**
Hello!

I've been using this player I made in favor of the default one and I'm really digging it. So I decided to share it with you, and maybe see if you're interested in merging. Don't feel pressured though, I made it mostly for me, because I wanted some sort of video rotation support and most importantly, when I changed my volume levels, I wanted it to be persistent the next time I watched some other stream or replay. :laughing: 

Anyway, here are the changes:

* **I'm using [Plyr](https://plyr.io/) for the UI**. Well, mostly because it's pretty, lightweight, and customizable ~~and I suck at CSS~~.
* **I'm using [flv.js](https://github.com/bilibili/flv.js)** (to reproduce live streams only). I've always had insane stuttering on LiveMe with HLS live streams. And that was before I found out the official app actually uses the FLV stream, that's why is doesn't stutter there. However, their website still use HLS so if I watch there, it still lags like crap for me.
* I tried to keep the watching experience simple and effective, just like the native player.
* **Keyboard shortcuts**: A bunch of them! My favorite, like I mentioned before, is the video rotation one. It'd be ideal if it rotated automatically by detecting landscape mode, but I'm not sure if even the official app does that. Perhaps I could try implementing that in the future... Anyway, if you hit `Alt` + `→`, the player window will rotate 90 degrees forward and also adjust the window based on the video dimensions. Same thing for `Alt` + `←`, but this one does 90 degrees backwards. You can even watch a video upside-down now if you want! A feature much requested by the australians.

**However**, two shortcuts had to be replaced (`K` and `L`), because one of them (`K`) was [already being used by Plyr](https://github.com/sampotts/plyr/tree/v3.5.3#shortcuts), and unfortunately there is no way to disable it. So instead of `K` and `L` to seek backward/forward by 10 seconds, it's now `A` and `D`, respectively. Here's a screenshot of all shortcuts:

keyboard-shortcuts

And... I think that's pretty much it. If you need more details of a specific change was made, you can try to check the commit's description, or you can just ask me and I'll try to answer you asap.

Let me know what you think! Thanks.

### CODE REVIEW

**Comment by bem13** [comment]
Do you think it would be possible to implement the idea in https://github.com/thecoder75/liveme-pro-tools/issues/73 in this? :)

**Comment by mustang-sally** [comment]
I think it is feasible since it doesn't rely on the native player anymore. Perhaps by adding some markers in the progress bar wherever there is a comment, or something like that.

**Comment by bem13** [comment]
I think that would be neat, provided it's configurable so people who don't want it aren't annoyed by it.

**Comment by thecoder75** [comment]
I checked out the homepage for plyr.io and really like how the player looks.  Approving because the UI alone of the player is what I've always wanted to have in the app and also cause it finally solves one of the longest/oldest requests for video rotation.

**Pull request merged**
